services:

  microservices:
    command: bash
    build:
        context: .
        dockerfile: Dockerfile
    image: sfl/microservice-architecture

  service-one:
    image: sfl/microservice-architecture
    command: service-one
    env_file: .env
    ports:
      - 8001:8080

  service-two:
    image: sfl/microservice-architecture
    command: service-two
    env_file: .env
    ports:
      - 8002:8080